"""Shared helpers for PlaScan environment setup scripts."""

from __future__ import annotations

import json
import os
import platform
import shlex
import subprocess
import sys
from pathlib import Path
from typing import Iterable


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def default_output_dir() -> Path:
    return repo_root() / "build" / "env"


def host_platform() -> str:
    test_override = os.environ.get("_PLASCAN_TEST_HOST_PLATFORM", "").strip().lower()
    if test_override in {"windows", "linux", "macos"}:
        return test_override

    system = platform.system().lower()
    if system.startswith("win"):
        return "windows"
    if system == "darwin":
        return "macos"
    return "linux"


def quote_command(cmd: Iterable[str]) -> str:
    if host_platform() == "windows":
        return subprocess.list2cmdline(list(cmd))
    return " ".join(shlex.quote(part) for part in cmd)


def run(
    cmd: list[str],
    *,
    dry_run: bool = False,
    env: dict[str, str] | None = None,
    cwd: Path | None = None,
) -> None:
    print(f"+ {quote_command(cmd)}")
    if dry_run:
        return
    subprocess.run(cmd, check=True, env=env, cwd=cwd)


def capture(
    cmd: list[str],
    *,
    dry_run: bool = False,
    env: dict[str, str] | None = None,
    cwd: Path | None = None,
) -> str:
    print(f"+ {quote_command(cmd)}")
    if dry_run:
        return ""
    return subprocess.check_output(cmd, text=True, env=env, cwd=cwd).strip()


def python_executable_from_prefix(prefix: Path) -> Path:
    if host_platform() == "windows":
        return prefix / "python.exe"
    return prefix / "bin" / "python"


def cmake_path(path: str | Path) -> str:
    return Path(path).resolve().as_posix()


def powershell_utf8_prelude() -> list[str]:
    return [
        "$utf8NoBom = [System.Text.UTF8Encoding]::new($false)",
        "[Console]::InputEncoding = $utf8NoBom",
        "[Console]::OutputEncoding = $utf8NoBom",
        "$OutputEncoding = $utf8NoBom",
        '$env:PYTHONUTF8 = "1"',
        '$env:PYTHONIOENCODING = "utf-8"',
        'if ($env:OS -eq "Windows_NT" -and (Get-Command chcp.com -ErrorAction SilentlyContinue))',
        "{",
        "    & chcp.com 65001 > $null",
        "}",
    ]


def write_env_files(output_dir: Path, values: dict[str, str], *, stem: str = "plascan-env") -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    clean_values = {key: str(value) for key, value in values.items() if value}

    json_path = output_dir / f"{stem}.json"
    json_path.write_text(json.dumps(clean_values, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    cmake_lines = ["# Generated by scripts/env. Do not commit machine-local paths."]
    cache_types = {
        "PLASCAN_TORCH_DIR": "PATH",
        "Torch_DIR": "PATH",
        "CUDAToolkit_ROOT": "PATH",
        "CUDA_TOOLKIT_ROOT_DIR": "PATH",
        "CMAKE_CUDA_COMPILER": "FILEPATH",
        "CMAKE_TOOLCHAIN_FILE": "FILEPATH",
        "VCPKG_TARGET_TRIPLET": "STRING",
    }
    for key, value in clean_values.items():
        if key in cache_types:
            cache_type = cache_types[key]
            cmake_value = cmake_path(value) if cache_type in {"PATH", "FILEPATH"} else value
            cmake_lines.append(f'set({key} "{cmake_value}" CACHE {cache_type} "PlaScan environment")')
    (output_dir / f"{stem}.cmake").write_text("\n".join(cmake_lines) + "\n", encoding="utf-8")

    shell_lines = ["# Generated by scripts/env. Source this file before running PlaScan tools."]
    for key, value in clean_values.items():
        shell_lines.append(f'export {key}="{value}"')
    (output_dir / f"{stem}.sh").write_text("\n".join(shell_lines) + "\n", encoding="utf-8")

    ps_lines = [
        "# Generated by scripts/env. Dot-source this file before running PlaScan tools.",
        *powershell_utf8_prelude(),
    ]
    for key, value in clean_values.items():
        escaped = value.replace("`", "``").replace('"', '`"')
        ps_lines.append(f'$env:{key} = "{escaped}"')
    (output_dir / f"{stem}.ps1").write_text("\n".join(ps_lines) + "\n", encoding="utf-8")

    print(f"Wrote environment files to {output_dir}")
    return json_path


def load_env_json(path: Path) -> dict[str, str]:
    if not path.exists():
        raise FileNotFoundError(f"environment file not found: {path}")
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"environment file must contain a JSON object: {path}")
    return {str(key): str(value) for key, value in data.items() if value}


def merged_environment(values: dict[str, str]) -> dict[str, str]:
    env = os.environ.copy()
    env.update(values)
    return env


def fail(message: str) -> None:
    print(f"error: {message}", file=sys.stderr)
    raise SystemExit(2)
