#include "ProjectWorkflowUtils.h"

#include "filtering/SparsePointCloudProcessor.h"
#include "TerrainPipeline.h"

#include <QDateTime>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QJsonDocument>

namespace xjw::gui::project {

namespace {

bool loadJsonObjectFile(const QString &path,
                        QJsonObject *object,
                        QString *errorMessage = nullptr)
{
    if (!object)
    {
        if (errorMessage)
        {
            *errorMessage = QStringLiteral("内部错误：缺少 JSON 输出对象");
        }
        return false;
    }

    QFile file(path);
    if (!file.open(QIODevice::ReadOnly))
    {
        if (errorMessage)
        {
            *errorMessage = QStringLiteral("无法读取点级结果文件: %1").arg(path);
        }
        return false;
    }

    const QJsonDocument doc = QJsonDocument::fromJson(file.readAll());
    file.close();
    if (!doc.isObject())
    {
        if (errorMessage)
        {
            *errorMessage = QStringLiteral("点级结果文件格式无效: %1").arg(path);
        }
        return false;
    }

    *object = doc.object();
    return true;
}

std::vector<xjw::SparsePointCloudPoint> sparsePointsFromJson(const QJsonArray &pointsArray)
{
    std::vector<xjw::SparsePointCloudPoint> points;
    points.reserve(pointsArray.size());
    for (const QJsonValue &value : pointsArray)
    {
        const QJsonObject pointObj = value.toObject();
        const QJsonArray xyz = pointObj.value(QStringLiteral("point_xyz")).toArray();
        if (xyz.size() < 3)
        {
            continue;
        }

        xjw::SparsePointCloudPoint point;
        point.x = xyz.at(0).toDouble();
        point.y = xyz.at(1).toDouble();
        point.z = xyz.at(2).toDouble();
        point.rmsReprojPx = pointObj.value(QStringLiteral("rms_reproj_px")).toDouble(
            pointObj.value(QStringLiteral("rms_after")).toDouble());
        point.minTriAngleDeg = pointObj.value(QStringLiteral("min_tri_angle_deg")).toDouble();
        point.trackLen = pointObj.value(QStringLiteral("track_len")).toInt(0);
        points.push_back(point);
    }
    return points;
}

QJsonArray sparsePointsToJson(const std::vector<xjw::SparsePointCloudPoint> &points)
{
    QJsonArray array;
    for (const xjw::SparsePointCloudPoint &point : points)
    {
        QJsonObject object;
        QJsonArray xyz;
        xyz.append(point.x);
        xyz.append(point.y);
        xyz.append(point.z);
        object[QStringLiteral("point_xyz")] = xyz;
        object[QStringLiteral("rms_reproj_px")] = point.rmsReprojPx;
        object[QStringLiteral("min_tri_angle_deg")] = point.minTriAngleDeg;
        object[QStringLiteral("track_len")] = point.trackLen;
        array.append(object);
    }
    return array;
}

bool writeSparsePointCloudPly(const QString &path,
                              const std::vector<xjw::SparsePointCloudPoint> &points,
                              QString *errorMessage = nullptr)
{
    QFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Truncate))
    {
        if (errorMessage)
        {
            *errorMessage = QStringLiteral("无法写入稀疏点云文件: %1").arg(path);
        }
        return false;
    }

    QByteArray header;
    header += "ply\n";
    header += "format ascii 1.0\n";
    header += "comment generated by plascan sparse point processor\n";
    header += QStringLiteral("element vertex %1\n").arg(points.size()).toUtf8();
    header += "property float x\n";
    header += "property float y\n";
    header += "property float z\n";
    header += "end_header\n";
    file.write(header);

    for (const xjw::SparsePointCloudPoint &point : points)
    {
        file.write(QStringLiteral("%1 %2 %3\n")
                       .arg(point.x, 0, 'f', 6)
                       .arg(point.y, 0, 'f', 6)
                       .arg(point.z, 0, 'f', 6)
                       .toUtf8());
    }
    file.close();
    return true;
}

QJsonObject makeSparsePointSidecar(QJsonObject sourceRoot,
                                   const std::vector<xjw::SparsePointCloudPoint> &points,
                                   const QString &operation,
                                   const QJsonObject &settings,
                                   const QJsonObject &summary,
                                   const QStringList &selectedImages,
                                   const QString &parentSidecar)
{
    sourceRoot[QStringLiteral("created_at")] = QDateTime::currentDateTimeUtc().toString(Qt::ISODate);
    sourceRoot[QStringLiteral("operation")] = operation;
    sourceRoot[QStringLiteral("settings")] = settings;
    sourceRoot[QStringLiteral("summary")] = summary;
    sourceRoot[QStringLiteral("selected_images")] = QJsonArray::fromStringList(selectedImages);
    sourceRoot[QStringLiteral("parent_sidecar")] = parentSidecar;
    sourceRoot[QStringLiteral("point_count")] = static_cast<int>(points.size());
    sourceRoot[QStringLiteral("points")] = sparsePointsToJson(points);
    return sourceRoot;
}

} // namespace

QString sparseOperationDisplayName(const QString &operation)
{
    if (operation == QLatin1String("triangulation"))
    {
        return QStringLiteral("初始稀疏点云");
    }
    if (operation == QLatin1String("outlier_removal"))
    {
        return QStringLiteral("离群点剔除");
    }
    if (operation == QLatin1String("sparse_refine"))
    {
        return QStringLiteral("稀疏点云精修");
    }
    if (operation == QLatin1String("bundle_adjust"))
    {
        return QStringLiteral("平差稀疏点云");
    }
    if (operation == QLatin1String("local_optim") || operation == QLatin1String("spatial_cleanup"))
    {
        return QStringLiteral("空间清理点云");
    }
    return QStringLiteral("稀疏点云");
}

int findLatestAtResultIndex(const QJsonObject &meta,
                            const QString &operation)
{
    const QJsonArray results = meta.value(QStringLiteral("aerial_triangulation_results")).toArray();
    for (int index = results.size() - 1; index >= 0; --index)
    {
        const QJsonObject record = results.at(index).toObject();
        if (!operation.isEmpty())
        {
            const QString recordOperation = record.value(QStringLiteral("operation")).toString();
            if (!recordOperation.isEmpty() && recordOperation != operation)
            {
                continue;
            }
        }
        return index;
    }
    return -1;
}

bool writeJsonObjectFile(const QString &path,
                         const QJsonObject &object,
                         QString *errorMessage)
{
    const OperationResult result = writeJsonObjectFileResult(path, object);
    if (!result.ok && errorMessage)
    {
        *errorMessage = result.errorMessage;
    }
    return result.ok;
}

OperationResult writeJsonObjectFileResult(const QString &path,
                                          const QJsonObject &object)
{
    QFile file(path);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Truncate))
    {
        return {false, QStringLiteral("无法写入文件: %1").arg(path)};
    }

    file.write(QJsonDocument(object).toJson(QJsonDocument::Indented));
    file.close();
    return {true, QString()};
}

TerrainPipelineResult runDemProducts(const QString &sparsePath,
                                     const QString &outputDir,
                                     double demResolution,
                                     const QString &demType,
                                     bool genPointCloud)
{
    TerrainPipelineResult result;
    result.ok = xjw::TerrainPipeline::generateDemProducts(sparsePath,
                                                          outputDir,
                                                          demResolution,
                                                          demType,
                                                          genPointCloud,
                                                          &result.payload,
                                                          &result.error);
    return result;
}

TerrainPipelineResult runOrthoProduct(const QStringList &images,
                                      const QString &demPath,
                                      const QString &outputPath,
                                      double resolution,
                                      const QJsonObject &projectMeta)
{
    TerrainPipelineResult result;
    result.ok = xjw::TerrainPipeline::generateOrthoProduct(images,
                                                           demPath,
                                                           outputPath,
                                                           resolution,
                                                           projectMeta,
                                                           &result.payload,
                                                           &result.error);
    return result;
}

bool resolveSparsePointContext(const QJsonObject &meta,
                               int requestedIndex,
                               SparsePointContext *context,
                               QString *errorMessage)
{
    if (!context)
    {
        if (errorMessage)
        {
            *errorMessage = QStringLiteral("内部错误：缺少稀疏点上下文");
        }
        return false;
    }

    const QJsonArray results = meta.value(QStringLiteral("aerial_triangulation_results")).toArray();
    if (results.isEmpty())
    {
        if (errorMessage)
        {
            *errorMessage = QStringLiteral("当前项目中还没有可用于处理的稀疏点云结果");
        }
        return false;
    }

    if (requestedIndex >= 0 && requestedIndex < results.size())
    {
        const QJsonObject record = results.at(requestedIndex).toObject();
        const QJsonObject files = record.value(QStringLiteral("files")).toObject();
        QString sidecarPath = files.value(QStringLiteral("sparse_cloud_points_json")).toString();
        const QString outputDir = record.value(QStringLiteral("output_dir")).toString();
        if (sidecarPath.isEmpty() && !outputDir.isEmpty())
        {
            const QString candidate = QDir(outputDir).filePath(QStringLiteral("sparse_cloud_points.json"));
            if (QFileInfo::exists(candidate))
            {
                sidecarPath = candidate;
            }
        }

        if (!sidecarPath.isEmpty() && QFileInfo::exists(sidecarPath))
        {
            context->sourceResultIndex = requestedIndex;
            context->outputDir = outputDir;
            context->sparseCloudPath = files.value(QStringLiteral("sparse_cloud_xyz")).toString();
            context->sidecarPath = sidecarPath;
            context->selectedImages.clear();
            for (const QJsonValue &imageValue : record.value(QStringLiteral("selected_images")).toArray())
            {
                context->selectedImages.append(imageValue.toString());
            }
            return true;
        }
    }

    for (int index = results.size() - 1; index >= 0; --index)
    {
        const QJsonObject record = results.at(index).toObject();
        const QJsonObject files = record.value(QStringLiteral("files")).toObject();
        QString sidecarPath = files.value(QStringLiteral("sparse_cloud_points_json")).toString();
        const QString outputDir = record.value(QStringLiteral("output_dir")).toString();
        if (sidecarPath.isEmpty() && !outputDir.isEmpty())
        {
            const QString candidate = QDir(outputDir).filePath(QStringLiteral("sparse_cloud_points.json"));
            if (QFileInfo::exists(candidate))
            {
                sidecarPath = candidate;
            }
        }

        if (sidecarPath.isEmpty() || !QFileInfo::exists(sidecarPath))
        {
            continue;
        }

        context->sourceResultIndex = index;
        context->outputDir = outputDir;
        context->sparseCloudPath = files.value(QStringLiteral("sparse_cloud_xyz")).toString();
        context->sidecarPath = sidecarPath;
        context->selectedImages.clear();
        for (const QJsonValue &imageValue : record.value(QStringLiteral("selected_images")).toArray())
        {
            context->selectedImages.append(imageValue.toString());
        }
        return true;
    }

    if (errorMessage)
    {
        *errorMessage = QStringLiteral("所选稀疏点云结果缺少点级 sidecar，无法继续执行该操作");
    }
    return false;
}

SparsePointContextResult resolveSparsePointContextResult(const QJsonObject &meta,
                                                         int requestedIndex)
{
    SparsePointContextResult result;
    QString errorMessage;
    result.status.ok = resolveSparsePointContext(meta,
                                                 requestedIndex,
                                                 &result.context,
                                                 &errorMessage);
    result.status.errorMessage = errorMessage;
    return result;
}

bool runSparsePointOutlierRemoval(const SparsePointContext &context,
                                  const QJsonObject &settings,
                                  const QString &outputDir,
                                  SparsePointOperationResult *result,
                                  QString *errorMessage)
{
    if (!result)
    {
        if (errorMessage)
        {
            *errorMessage = QStringLiteral("内部错误：缺少输出对象");
        }
        return false;
    }

    QJsonObject sourceRoot;
    if (!loadJsonObjectFile(context.sidecarPath, &sourceRoot, errorMessage))
    {
        return false;
    }

    std::vector<xjw::SparsePointCloudPoint> points = sparsePointsFromJson(sourceRoot.value(QStringLiteral("points")).toArray());
    if (points.empty())
    {
        if (errorMessage)
        {
            *errorMessage = QStringLiteral("点级 sidecar 中没有可处理的稀疏点");
        }
        return false;
    }

    const int inputCount = static_cast<int>(points.size());
    QJsonObject summary;
    summary[QStringLiteral("input_points")] = inputCount;

    xjw::SparsePointCloudFilterOptions options;
    options.filterByReprojError = settings.value(QStringLiteral("filterByReprojError")).toBool();
    options.maxReprojError = settings.value(QStringLiteral("maxReprojError")).toDouble(2.5);
    options.filterByTrackLen = settings.value(QStringLiteral("filterByTrackLen")).toBool();
    options.minTrackLen = settings.value(QStringLiteral("minTrackLen")).toInt(3);
    options.filterByTriAngle = settings.value(QStringLiteral("filterByTriAngle")).toBool();
    options.minTriAngleDeg = settings.value(QStringLiteral("minTriAngleDeg")).toDouble(2.0);
    options.filterByStatistical = settings.value(QStringLiteral("filterByStatistical")).toBool();
    options.statK = settings.value(QStringLiteral("statK")).toInt(16);
    options.statStdDevMul = settings.value(QStringLiteral("statStdDevMul")).toDouble(2.5);
    options.filterByDensity = settings.value(QStringLiteral("filterByDensity")).toBool(false);
    options.densityRadius = settings.value(QStringLiteral("densityRadius")).toDouble(0.5);
    options.densityMinNeighbors = settings.value(QStringLiteral("densityMinNeighbors")).toInt(5);

    xjw::SparsePointCloudOptimizeOptions optimizeOptions;
    optimizeOptions.filterOptions = options;
    const xjw::SparsePointCloudOptimizeResult optimizeResult =
        xjw::SparsePointCloudProcessor::optimize(points, optimizeOptions);
    points = optimizeResult.points;
    const xjw::SparsePointCloudFilterStats stats = optimizeResult.rounds.empty()
        ? xjw::SparsePointCloudFilterStats{}
        : optimizeResult.rounds.front().filterStats;
    summary[QStringLiteral("removed_by_reproj")] = stats.removedByReprojError;
    summary[QStringLiteral("removed_by_track_len")] = stats.removedByTrackLen;
    summary[QStringLiteral("removed_by_tri_angle")] = stats.removedByTriAngle;
    summary[QStringLiteral("removed_by_statistical")] = stats.removedByStatistical;
    summary[QStringLiteral("removed_by_density")] = stats.removedByDensity;
    summary[QStringLiteral("output_points")] = static_cast<int>(points.size());
    summary[QStringLiteral("removed_total")] = inputCount - static_cast<int>(points.size());
    if (points.empty())
    {
        if (errorMessage)
        {
            *errorMessage = QStringLiteral("过滤结果为空，请放宽阈值后重试");
        }
        return false;
    }

    QDir().mkpath(outputDir);
    const QString sparseCloudPath = QDir(outputDir).filePath(QStringLiteral("sparse_cloud_filtered.ply"));
    const QString sidecarPath = QDir(outputDir).filePath(QStringLiteral("sparse_cloud_points.json"));
    if (!writeSparsePointCloudPly(sparseCloudPath, points, errorMessage))
    {
        return false;
    }

    const QJsonObject sidecar = makeSparsePointSidecar(sourceRoot,
                                                       points,
                                                       QStringLiteral("outlier_removal"),
                                                       settings,
                                                       summary,
                                                       context.selectedImages,
                                                       context.sidecarPath);
    if (!writeJsonObjectFile(sidecarPath, sidecar, errorMessage))
    {
        return false;
    }

    result->outputDir = outputDir;
    result->sparseCloudPath = sparseCloudPath;
    result->sidecarPath = sidecarPath;
    result->inputCount = inputCount;
    result->outputCount = static_cast<int>(points.size());
    QJsonObject files;
    files[QStringLiteral("sparse_cloud_points_json")] = sidecarPath;
    result->extraRecord[QStringLiteral("files")] = files;
    result->extraRecord[QStringLiteral("source")] = QStringLiteral("sparse_outlier_removal");
    result->extraRecord[QStringLiteral("operation")] = QStringLiteral("outlier_removal");
    result->extraRecord[QStringLiteral("source_result_index")] = context.sourceResultIndex;
    result->extraRecord[QStringLiteral("operation_settings")] = settings;
    result->extraRecord[QStringLiteral("operation_summary")] = summary;
    return true;
}

bool runSparsePointLocalOptim(const SparsePointContext &context,
                              const QJsonObject &settings,
                              const QString &outputDir,
                              SparsePointOperationResult *result,
                              QString *errorMessage)
{
    if (!result)
    {
        if (errorMessage)
        {
            *errorMessage = QStringLiteral("内部错误：缺少输出对象");
        }
        return false;
    }

    QJsonObject sourceRoot;
    if (!loadJsonObjectFile(context.sidecarPath, &sourceRoot, errorMessage))
    {
        return false;
    }

    std::vector<xjw::SparsePointCloudPoint> points =
        sparsePointsFromJson(sourceRoot.value(QStringLiteral("points")).toArray());
    if (points.empty())
    {
        if (errorMessage)
        {
            *errorMessage = QStringLiteral("点级 sidecar 中没有可处理的稀疏点");
        }
        return false;
    }

    const int inputCount = static_cast<int>(points.size());

    xjw::SparseCloudLocalOptimOptions options;
    options.voxelSize = settings.value(QStringLiteral("voxelSize")).toDouble(0.0);
    options.minVoxelPoints = settings.value(QStringLiteral("minVoxelPoints")).toInt(2);
    options.localReprojFilter = settings.value(QStringLiteral("localReprojFilter")).toBool(true);
    options.localReprojStdMul = settings.value(QStringLiteral("localReprojStdMul")).toDouble(2.5);
    options.deduplicationRadius = settings.value(QStringLiteral("deduplicationRadius")).toDouble(-1.0);

    const xjw::SparsePointCloudSpatialCleanupResult optResult =
        xjw::SparsePointCloudProcessor::spatialCleanup(&points, options);

    if (points.empty())
    {
        if (errorMessage)
        {
            *errorMessage = QStringLiteral("空间清理后没有剩余稀疏点，请降低过滤强度后重试");
        }
        return false;
    }

    QDir().mkpath(outputDir);
    const QString sparseCloudPath = QDir(outputDir).filePath(QStringLiteral("sparse_cloud_spatial_cleanup.ply"));
    const QString sidecarPath = QDir(outputDir).filePath(QStringLiteral("sparse_cloud_points.json"));
    if (!writeSparsePointCloudPly(sparseCloudPath, points, errorMessage))
    {
        return false;
    }

    QJsonObject summary;
    summary[QStringLiteral("input_points")] = optResult.inputPoints;
    summary[QStringLiteral("output_points")] = optResult.outputPoints;
    summary[QStringLiteral("removed_by_voxel_isolation")] = optResult.removedByVoxelIsolation;
    summary[QStringLiteral("removed_by_local_reproj")] = optResult.removedByLocalReproj;
    summary[QStringLiteral("removed_by_deduplication")] = optResult.removedByDeduplication;
    summary[QStringLiteral("removed_total")] =
        optResult.removedByVoxelIsolation + optResult.removedByLocalReproj + optResult.removedByDeduplication;

    const QJsonObject sidecar = makeSparsePointSidecar(sourceRoot,
                                                       points,
                                                       QStringLiteral("spatial_cleanup"),
                                                       settings,
                                                       summary,
                                                       context.selectedImages,
                                                       context.sidecarPath);
    if (!writeJsonObjectFile(sidecarPath, sidecar, errorMessage))
    {
        return false;
    }

    result->outputDir = outputDir;
    result->sparseCloudPath = sparseCloudPath;
    result->sidecarPath = sidecarPath;
    result->inputCount = inputCount;
    result->outputCount = static_cast<int>(points.size());
    QJsonObject files;
    files[QStringLiteral("sparse_cloud_points_json")] = sidecarPath;
    result->extraRecord[QStringLiteral("files")] = files;
    result->extraRecord[QStringLiteral("source")] = QStringLiteral("sparse_spatial_cleanup");
    result->extraRecord[QStringLiteral("operation")] = QStringLiteral("spatial_cleanup");
    result->extraRecord[QStringLiteral("source_result_index")] = context.sourceResultIndex;
    result->extraRecord[QStringLiteral("operation_settings")] = settings;
    result->extraRecord[QStringLiteral("operation_summary")] = summary;
    return true;
}

bool runSparsePointRefine(const SparsePointContext &context,
                          const QJsonObject &settings,
                          const QString &outputDir,
                          SparsePointOperationResult *result,
                          QString *errorMessage)
{
    if (!result)
    {
        if (errorMessage)
        {
            *errorMessage = QStringLiteral("内部错误：缺少输出对象");
        }
        return false;
    }

    QJsonObject sourceRoot;
    if (!loadJsonObjectFile(context.sidecarPath, &sourceRoot, errorMessage))
    {
        return false;
    }

    const std::vector<xjw::SparsePointCloudPoint> basePoints =
        sparsePointsFromJson(sourceRoot.value(QStringLiteral("points")).toArray());
    if (basePoints.empty())
    {
        if (errorMessage)
        {
            *errorMessage = QStringLiteral("点级 sidecar 中没有可精修的稀疏点");
        }
        return false;
    }

    xjw::SparsePointCloudOptimizeOptions options;
    options.filterOptions.filterByReprojError = settings.value(QStringLiteral("filterByReprojError")).toBool(true);
    options.filterOptions.maxReprojError = settings.value(QStringLiteral("maxReprojError")).toDouble(4.0);
    options.filterOptions.filterByTrackLen = settings.value(QStringLiteral("filterByTrackLen")).toBool(true);
    options.filterOptions.minTrackLen = settings.value(QStringLiteral("minTrackLen")).toInt(3);
    options.filterOptions.filterByTriAngle = settings.value(QStringLiteral("filterByTriAngle")).toBool(true);
    options.filterOptions.minTriAngleDeg = settings.value(QStringLiteral("minTriAngleDeg")).toDouble(
        settings.value(QStringLiteral("minAngle")).toDouble(2.0));
    options.filterOptions.filterByStatistical = settings.value(QStringLiteral("filterByStatistical")).toBool(true);
    options.filterOptions.statK = settings.value(QStringLiteral("statK")).toInt(
        settings.value(QStringLiteral("knnNeighbors")).toInt(20));
    options.filterOptions.statStdDevMul = settings.value(QStringLiteral("statStdDevMul")).toDouble(
        settings.value(QStringLiteral("stdDevMultiplier")).toDouble(2.0));
    options.filterOptions.filterByDensity = settings.value(QStringLiteral("filterByDensity")).toBool(false);
    options.filterOptions.densityRadius = settings.value(QStringLiteral("densityRadius")).toDouble(0.5);
    options.filterOptions.densityMinNeighbors = settings.value(QStringLiteral("densityMinNeighbors")).toInt(5);
    options.filterOptions.filterByNormalConsistency = settings.value(QStringLiteral("normalConsistency")).toBool(false);
    options.iterative = true;
    options.iterRounds = settings.value(QStringLiteral("iterRounds")).toInt(3);
    options.restartFromInputEachRound = settings.value(QStringLiteral("retriangulate")).toBool(false);
    options.tightenThresholds = false;
    options.enableSpatialCleanup = settings.value(QStringLiteral("enableSpatialCleanup")).toBool(false);
    options.spatialCleanupOptions.voxelSize = settings.value(QStringLiteral("voxelSize")).toDouble(0.0);
    options.spatialCleanupOptions.minVoxelPoints = settings.value(QStringLiteral("minVoxelPoints")).toInt(2);
    options.spatialCleanupOptions.localReprojFilter = settings.value(QStringLiteral("localReprojFilter")).toBool(true);
    options.spatialCleanupOptions.localReprojStdMul = settings.value(QStringLiteral("localReprojStdMul")).toDouble(2.5);
    options.spatialCleanupOptions.deduplicationRadius = settings.value(QStringLiteral("deduplicationRadius")).toDouble(-1.0);

    const xjw::SparsePointCloudOptimizeResult refineResult =
        xjw::SparsePointCloudProcessor::optimize(basePoints, options);

    if (refineResult.points.empty())
    {
        if (errorMessage)
        {
            *errorMessage = QStringLiteral("精修后没有剩余稀疏点，请降低过滤强度后重试");
        }
        return false;
    }

    QDir().mkpath(outputDir);
    const QString sparseCloudPath = QDir(outputDir).filePath(QStringLiteral("sparse_cloud_refined.ply"));
    const QString sidecarPath = QDir(outputDir).filePath(QStringLiteral("sparse_cloud_points.json"));
    if (!writeSparsePointCloudPly(sparseCloudPath, refineResult.points, errorMessage))
    {
        return false;
    }

    QJsonObject summary;
    QJsonArray roundSummaries;
    for (const xjw::SparsePointCloudOptimizeRound &round : refineResult.rounds)
    {
        QJsonObject roundSummary;
        roundSummary[QStringLiteral("round")] = round.round;
        roundSummary[QStringLiteral("input_points")] = round.inputPoints;
        roundSummary[QStringLiteral("max_reproj_error")] = round.filterOptions.maxReprojError;
        roundSummary[QStringLiteral("min_tri_angle_deg")] = round.filterOptions.minTriAngleDeg;
        roundSummary[QStringLiteral("min_track_len")] = round.filterOptions.minTrackLen;
        roundSummary[QStringLiteral("stat_stddev_mul")] = round.filterOptions.statStdDevMul;
        roundSummary[QStringLiteral("removed_by_reproj")] = round.filterStats.removedByReprojError;
        roundSummary[QStringLiteral("removed_by_track_len")] = round.filterStats.removedByTrackLen;
        roundSummary[QStringLiteral("removed_by_tri_angle")] = round.filterStats.removedByTriAngle;
        roundSummary[QStringLiteral("removed_by_statistical")] = round.filterStats.removedByStatistical;
        roundSummary[QStringLiteral("removed_by_normal_consistency")] = round.filterStats.removedByNormalConsistency;
        roundSummary[QStringLiteral("removed_by_density")] = round.filterStats.removedByDensity;
        roundSummary[QStringLiteral("output_points")] = round.outputPoints;
        roundSummaries.append(roundSummary);
    }
    summary[QStringLiteral("input_points")] = refineResult.inputPoints;
    summary[QStringLiteral("output_points")] = refineResult.outputPoints;
    summary[QStringLiteral("removed_total")] = refineResult.removedTotal;
    summary[QStringLiteral("iter_rounds")] = options.iterRounds;
    summary[QStringLiteral("retriangulate")] = options.restartFromInputEachRound;
    summary[QStringLiteral("normal_consistency")] = options.filterOptions.filterByNormalConsistency;
    summary[QStringLiteral("spatial_cleanup")] = options.enableSpatialCleanup;
    summary[QStringLiteral("rounds")] = roundSummaries;

    const QJsonObject sidecar = makeSparsePointSidecar(sourceRoot,
                                                       refineResult.points,
                                                       QStringLiteral("sparse_refine"),
                                                       settings,
                                                       summary,
                                                       context.selectedImages,
                                                       context.sidecarPath);
    if (!writeJsonObjectFile(sidecarPath, sidecar, errorMessage))
    {
        return false;
    }

    result->outputDir = outputDir;
    result->sparseCloudPath = sparseCloudPath;
    result->sidecarPath = sidecarPath;
    result->inputCount = refineResult.inputPoints;
    result->outputCount = refineResult.outputPoints;
    QJsonObject files;
    files[QStringLiteral("sparse_cloud_points_json")] = sidecarPath;
    result->extraRecord[QStringLiteral("files")] = files;
    result->extraRecord[QStringLiteral("source")] = QStringLiteral("sparse_cloud_refine");
    result->extraRecord[QStringLiteral("operation")] = QStringLiteral("sparse_refine");
    result->extraRecord[QStringLiteral("source_result_index")] = context.sourceResultIndex;
    result->extraRecord[QStringLiteral("operation_settings")] = settings;
    result->extraRecord[QStringLiteral("operation_summary")] = summary;
    return true;
}

QJsonArray summarizeAtResults(const QJsonObject &meta)
{
    const QJsonArray atArray = meta.value(QStringLiteral("aerial_triangulation_results")).toArray();
    QJsonArray summary;
    for (int i = 0; i < atArray.size(); ++i)
    {
        const QJsonObject at = atArray.at(i).toObject();
        const QJsonObject files = at.value(QStringLiteral("files")).toObject();
        QJsonObject item;
        item[QStringLiteral("index")] = i;
        item[QStringLiteral("created_at")] = at.value(QStringLiteral("created_at")).toString();
        item[QStringLiteral("output_dir")] = at.value(QStringLiteral("output_dir")).toString();
        item[QStringLiteral("sparse_point_count")] = at.value(QStringLiteral("sparse_point_count")).toInt(0);
        const QJsonArray selImgs = at.value(QStringLiteral("selected_images")).toArray();
        item[QStringLiteral("image_count")] = selImgs.size();
        item[QStringLiteral("image0")] = selImgs.isEmpty() ? QString() : selImgs.first().toString();
        item[QStringLiteral("image1")] = selImgs.size() > 1 ? selImgs.last().toString() : QString();
        item[QStringLiteral("sparse_cloud_xyz")] = files.value(QStringLiteral("sparse_cloud_xyz")).toString();
        item[QStringLiteral("operation")] = at.value(QStringLiteral("operation")).toString(QStringLiteral("triangulation"));
        item[QStringLiteral("operation_display_name")] = at.value(QStringLiteral("operation_display_name")).toString(
            sparseOperationDisplayName(item.value(QStringLiteral("operation")).toString()));
        item[QStringLiteral("source_result_index")] = at.value(QStringLiteral("source_result_index")).toInt(-1);
        item[QStringLiteral("is_latest")] = (i == atArray.size() - 1);
        if (at.contains(QStringLiteral("operation_summary")))
        {
            item[QStringLiteral("operation_summary")] = at.value(QStringLiteral("operation_summary"));
        }

        const QString opLabel = sparseOperationDisplayName(item.value(QStringLiteral("operation")).toString());
        const QString dirName = QFileInfo(item.value(QStringLiteral("output_dir")).toString()).fileName();
        QString displayName = QStringLiteral("#%1 %2").arg(i).arg(opLabel);
        if (item.value(QStringLiteral("sparse_point_count")).toInt(0) > 0)
        {
            displayName += QStringLiteral("  [%1 点]").arg(item.value(QStringLiteral("sparse_point_count")).toInt());
        }
        if (!dirName.isEmpty())
        {
            displayName += QStringLiteral("  (%1)").arg(dirName);
        }
        if (item.value(QStringLiteral("source_result_index")).toInt(-1) >= 0)
        {
            displayName += QStringLiteral("  [源 #%1]").arg(item.value(QStringLiteral("source_result_index")).toInt());
        }
        if (item.value(QStringLiteral("is_latest")).toBool())
        {
            displayName += QStringLiteral("  [当前]");
        }
        item[QStringLiteral("display_name")] = displayName;
        summary.append(item);
    }
    return summary;
}

} // namespace xjw::gui::project