# 链接核心库（仅当 core 可用）
if(TARGET plascan_common_project)
  target_link_libraries(plascan_gui PRIVATE plascan_common_project)
endif()

if(EXISTS ${CMAKE_SOURCE_DIR}/src/core/CMakeLists.txt)
  if(TARGET superpoint)
    message(STATUS "plascan_gui: linking against superpoint target")
    target_link_libraries(plascan_gui PRIVATE superpoint)
  else()
    message(WARNING "plascan_core superpoint target not available - GUI will build without SuperPoint")
  endif()

  if(TARGET feature_extractors_traditional)
    message(STATUS "plascan_gui: linking against feature_extractors_traditional target")
    target_link_libraries(plascan_gui PRIVATE feature_extractors_traditional)
  else()
    message(WARNING "plascan_core feature_extractors_traditional target not available - GUI will build without classic extractors")
  endif()

  if(TARGET superglue_matcher)
    message(STATUS "plascan_gui: linking against superglue_matcher target")
    target_link_libraries(plascan_gui PRIVATE superglue_matcher)
  else()
    message(WARNING "plascan_core superglue_matcher target not available - GUI will build without SuperGlue")
  endif()

  if(TARGET lightglue_matcher)
    message(STATUS "plascan_gui: linking against lightglue_matcher target")
    target_link_libraries(plascan_gui PRIVATE lightglue_matcher)
  else()
    message(WARNING "plascan_core lightglue_matcher target not available - GUI will build without LightGlue")
  endif()

  if(TARGET feature_match_traditional)
    message(STATUS "plascan_gui: linking against feature_match_traditional target")
    target_link_libraries(plascan_gui PRIVATE feature_match_traditional)
  else()
    message(WARNING "plascan_core feature_match_traditional target not available - GUI will build without classic matchers")
  endif()

  if(TARGET camera)
    message(STATUS "plascan_gui: linking against camera target")
    target_link_libraries(plascan_gui PRIVATE camera)
  else()
    message(WARNING "plascan_core camera target not available - 相机导入功能将不可用")
  endif()

  if(TARGET intersection)
    message(STATUS "plascan_gui: linking against intersection target")
    target_link_libraries(plascan_gui PRIVATE intersection)
  else()
    message(WARNING "plascan_core intersection target not available - 前方交汇功能将不可用")
  endif()

  if(TARGET bundle_adjust)
    message(STATUS "plascan_gui: linking against bundle_adjust target")
    target_link_libraries(plascan_gui PRIVATE bundle_adjust)
  else()
    message(WARNING "plascan_core bundle_adjust target not available - 光束法平差功能将不可用")
  endif()

  if(TARGET lidar)
    message(STATUS "plascan_gui: linking against lidar target")
    target_link_libraries(plascan_gui PRIVATE lidar)
  else()
    message(WARNING "plascan_core lidar target not available - LiDAR 辅助平差功能将不可用")
  endif()

  if(TARGET qc)
    message(STATUS "plascan_gui: linking against qc target")
    target_link_libraries(plascan_gui PRIVATE qc)
    target_include_directories(plascan_gui PRIVATE ${CMAKE_SOURCE_DIR}/src/core/qc)
  else()
    message(WARNING "plascan_core qc target not available - 重建质量报告功能将不可用")
  endif()

  if(TARGET control_points)
    message(STATUS "plascan_gui: linking against control_points target")
    target_link_libraries(plascan_gui PRIVATE control_points)
  else()
    message(WARNING "plascan_core control_points target not available - 标记点系统将不可用")
  endif()

  if(TARGET mask)
    message(STATUS "plascan_gui: linking against mask target")
    target_link_libraries(plascan_gui PRIVATE mask)
    target_include_directories(plascan_gui PRIVATE ${CMAKE_SOURCE_DIR}/src/core/mask)
  else()
    message(WARNING "plascan_core mask target not available - 照片蒙版功能将不可用")
  endif()

  if(TARGET plapoint::plapoint)
    message(STATUS "plascan_gui: linking against plapoint::plapoint")
    target_link_libraries(plascan_gui PRIVATE plapoint::plapoint)
  else()
    message(WARNING "plapoint::plapoint target not available - plapoint 点云功能将不可用")
  endif()

  if(TARGET overlap)
    message(STATUS "plascan_gui: linking against overlap target")
    target_link_libraries(plascan_gui PRIVATE overlap)
  else()
    message(WARNING "plascan_core overlap target not available - 重叠度分析功能将不可用")
  endif()

  if(TARGET terrain)
    message(STATUS "plascan_gui: linking against terrain target")
    target_link_libraries(plascan_gui PRIVATE terrain)
  else()
    message(WARNING "plascan_core terrain target not available - DEM/正射流程将不可用")
  endif()

  if(TARGET sfm)
    message(STATUS "plascan_gui: linking against sfm target")
    target_link_libraries(plascan_gui PRIVATE sfm)
  else()
    message(WARNING "plascan_core sfm target not available - 无相机先验空三流程将不可用")
  endif()

  if(TARGET matchphototask)
    message(STATUS "plascan_gui: linking against matchphototask target")
    target_link_libraries(plascan_gui PRIVATE matchphototask)
  else()
    message(WARNING "plascan_core matchphototask target not available - 连接点匹配任务将不可用")
  endif()

  if(TARGET mvs)
    message(STATUS "plascan_gui: linking against mvs target")
    target_link_libraries(plascan_gui PRIVATE mvs)
    target_include_directories(plascan_gui PRIVATE ${CMAKE_SOURCE_DIR}/src/core/mvs)
  else()
    message(WARNING "plascan_core mvs target not available - 稠密点云功能将不可用")
  endif()

  if(TARGET dense_match)
    message(STATUS "plascan_gui: linking against dense_match target")
    target_link_libraries(plascan_gui PRIVATE dense_match)
    target_include_directories(plascan_gui PRIVATE ${CMAKE_SOURCE_DIR}/src/core/dense_match)
  else()
    message(WARNING "plascan_core dense_match target not available - 密集匹配功能将不可用")
  endif()

  if(TARGET meshing)
    message(STATUS "plascan_gui: linking against meshing target")
    target_link_libraries(plascan_gui PRIVATE meshing)
    target_include_directories(plascan_gui PRIVATE ${CMAKE_SOURCE_DIR}/src/core/mesh)
  else()
    message(WARNING "plascan_core meshing target not available - 网格重建功能将不可用")
  endif()
else()
  message(WARNING "plascan_core target not found - GUI will build without core linkage")
endif()
