# GUI 源文件清单

set(GUI_SOURCES
  main.cpp
  config/AppConfigManager.cpp
  config/JsonMergeUtil.cpp
  config/ProjectUiConfigManager.cpp
  config/ProjectWorkflowConfigManager.cpp
  config/ProjectConfigManager.cpp
  config/settings/WindowStateManager.cpp
  config/settings/RecentProjectsManager.cpp
  config/settings/FileDialogStateManager.cpp
  config/settings/GlobalSettings.cpp
  config/settings/ProjectDialogJsonSettingBase.cpp
  config/settings/DialogSettingStore.cpp
  main_window/MainWindow.cpp
  main_window/MainWindow.ui
  main_window/ModelDropSupport.cpp
  main_window/MenuWorkflowController.cpp
  main_window/ReconstructionWorkflowController.cpp
  menu/MainMenu.cpp
  panels/LogPanel.cpp
  project/archive/PlascanArchive.cpp
  project/data/ProjectData.cpp
  project/data/ProjectFilesManager.cpp
  project/io/ProjectIO.cpp
  project/services/BundleAdjustService.cpp
  project/services/ProjectCameraImportService.cpp
  project/services/ProjectResourceCleanupService.cpp
  project/support/ProjectSupportUtils.cpp
  project/support/ProjectBundleAdjustExecution.cpp
  project/support/ProjectBundleAdjustWorkflow.cpp
  project/support/ProjectCameraInitialization.cpp
  project/support/ProjectDashboardSummary.cpp
  project/support/ProjectDenseWorkflowConfig.cpp
  project/support/ProjectMetadataOperations.cpp
  project/support/ProjectReferenceDatasets.cpp
  project/support/ProjectReferenceTerrainBa.cpp
  project/support/ProjectResultRecords.cpp
  project/support/ProjectSfmWorkflow.cpp
  project/support/ProjectSparseWorkflow.cpp
  project/support/ProjectSurveyControl.cpp
  project/support/ProjectWorkflowUtils.cpp
  project/support/ProjectWorkflowReports.cpp
  project/manager/ProjectManager.cpp
  project/manager/ProjectDenseReconstructionManager.cpp
  project/manager/ProjectModelManager.cpp
  project/manager/ProjectReconstructionManager.cpp
  project/manager/ProjectTaskDispatcher.cpp
  project/manager/ProjectUiCommands.cpp
  project/manager/ProjectSparseReconstructionManager.cpp
  project/manager/ProjectTerrainProductsManager.cpp
  project/manager/ProjectCameraSetupManager.cpp
  tasks/FeatureExtractionRunner.cpp
  views/LayerFeatureLoader.cpp
  views/LayerImageLoader.cpp
  views/LayerOverlayItems.cpp
  views/LayerRenderer.cpp
  widgets/CanvasWidget.cpp
  widgets/DataTreeWidget.cpp
  widgets/DataTreeWidget.ui
  widgets/ProjectDashboardWidget.cpp
  widgets/ReferencePanelWidget.cpp
  widgets/WindowPanel.cpp
  widgets/WindowPanel.ui
  widgets/ImageViewWidget.cpp
  widgets/ImageViewWidget.ui
  widgets/MatchLineOverlay.cpp
  widgets/DisparityHeatmapOverlay.cpp
  widgets/TaskStatusWidget.cpp
  widgets/DualImageViewer.cpp
  widgets/DualImageViewer.ui
  widgets/ObservationNetworkView.cpp
  widgets/WorkspaceCenterWidget.cpp
  widgets/WorkspaceCenterWidget.ui
  dialogs/MatchViewerDialog.cpp
  dialogs/MatchPairSelectorDialog.cpp
  dialogs/BundleAdjustDialog.cpp
  dialogs/CameraModel3DDialog.cpp
  dialogs/StereoProcessingDialog.cpp
  dialogs/OverlapAnalysisDialog.cpp
  dialogs/CreateDemDialog.cpp
  dialogs/MapProjectDialog.cpp
  dialogs/FeatureExtractionDialog.cpp
  dialogs/FeaturePairPlanner.cpp
  dialogs/VocabularyOverlapDialog.cpp
  dialogs/VocabularyOverlapDialog.ui
  dialogs/FeaturePointVisualizationDialog.cpp
  dialogs/FeatureMatchingDialog.cpp
  dialogs/ForwardIntersectionCheckDialog.cpp
  dialogs/ForwardIntersectionResultsDialog.cpp
  dialogs/DenseCloudDialog.cpp
  dialogs/ThreeDReconstructionDialog.cpp
  dialogs/ThreeDReconstructionDialog.ui
  dialogs/SparseCloudPostProcessDialog.cpp
  dialogs/MVSProgressDialog.cpp
  dialogs/WorkflowReportDialog.cpp
  dialogs/CameraConvertDialog.cpp
  dialogs/SurveyControlDialog.cpp
  dialogs/ObservationNetworkDialog.cpp
  dialogs/InitCameraPoseDialog.cpp
  dialogs/TriangulationDialog.cpp
  dialogs/DepthMapEstimateDialog.cpp
  dialogs/DepthFusionDialog.cpp
  dialogs/DenseCloudRefineDialog.cpp
  dialogs/MeshReconstructionDialog.cpp
  dialogs/TextureMappingDialog.cpp
  dialogs/ModelExportDialog.cpp
  dialogs/DenseMatchDialog.cpp
  dialogs/DenseMatchDialogUi.cpp
)

set(GUI_HEADERS
  config/AppConfigManager.h
  config/JsonMergeUtil.h
  config/ProjectUiConfigManager.h
  config/ProjectWorkflowConfigManager.h
  config/ProjectConfigManager.h
  config/settings/WindowStateManager.h
  config/settings/RecentProjectsManager.h
  config/settings/FileDialogStateManager.h
  config/settings/GlobalSettings.h
  config/settings/ProjectDialogJsonSettingBase.h
  config/settings/DialogSettingStore.h
  config/settings/DialogSettingKeys.h
  compat/QtTorchMacroGuard.h
  main_window/MainWindow.h
  main_window/ModelDropSupport.h
  main_window/MenuWorkflowController.h
  main_window/ReconstructionWorkflowController.h
  menu/MainMenu.h
  panels/LogPanel.h
  project/archive/PlascanArchive.h
  project/data/ProjectData.h
  project/data/ProjectFilesManager.h
  project/io/ProjectIO.h
  project/services/BundleAdjustService.h
  project/services/ProjectBaInputBuilder.h
  project/services/ProjectCameraImportService.h
  project/services/ProjectResourceCleanupService.h
  project/services/ProjectTriangulationService.h
  project/support/ProjectSupportUtils.h
  project/support/ProjectBundleAdjustExecution.h
  project/support/ProjectBundleAdjustWorkflow.h
  project/support/ProjectCameraInitialization.h
  project/support/ProjectDashboardSummary.h
  project/support/ProjectDenseWorkflowConfig.h
  project/support/ProjectMetadataOperations.h
  project/support/ProjectReferenceDatasets.h
  project/support/ProjectReferenceTerrainBa.h
  project/support/ProjectResultRecords.h
  project/support/ProjectSfmWorkflow.h
  project/support/ProjectSparseWorkflow.h
  project/support/ProjectSurveyControl.h
  project/support/ProjectWorkflowUtils.h
  project/support/ProjectWorkflowReports.h
  project/manager/ProjectManager.h
  project/manager/ProjectDenseReconstructionManager.h
  project/manager/ProjectModelManager.h
  project/manager/ProjectReconstructionManager.h
  project/manager/ProjectTaskDispatcher.h
  project/manager/ProjectUiCommands.h
  project/manager/ProjectSparseReconstructionManager.h
  project/manager/ProjectTerrainProductsManager.h
  project/manager/ProjectCameraSetupManager.h
  tasks/FeatureExtractionRunner.h
  tasks/GuiTaskRunner.h
  tasks/SFMService.h
  views/LayerFeatureLoader.h
  views/LayerImageLoader.h
  views/LayerOverlayItems.h
  views/LayerRenderer.h
  widgets/CanvasWidget.h
  widgets/DataTreeWidget.h
  widgets/ProjectDashboardWidget.h
  widgets/ReferencePanelWidget.h
  widgets/WindowPanel.h
  widgets/ImageViewWidget.h
  widgets/MatchLineOverlay.h
  widgets/DisparityHeatmapOverlay.h
  widgets/TaskStatusWidget.h
  widgets/DualImageViewer.h
  widgets/ObservationNetworkView.h
  widgets/WorkspaceCenterWidget.h
  dialogs/MatchViewerDialog.h
  dialogs/MatchPairSelectorDialog.h
  dialogs/BundleAdjustDialog.h
  dialogs/CameraModel3DDialog.h
  dialogs/StereoProcessingDialog.h
  dialogs/OverlapAnalysisDialog.h
  dialogs/CreateDemDialog.h
  dialogs/MapProjectDialog.h
  dialogs/FeatureExtractionDialog.h
  dialogs/FeaturePairPlanner.h
  dialogs/VocabularyOverlapDialog.h
  dialogs/FeaturePointVisualizationDialog.h
  dialogs/FeatureMatchingDialog.h
  dialogs/ForwardIntersectionCheckDialog.h
  dialogs/ForwardIntersectionResultsDialog.h
  dialogs/DenseCloudDialog.h
  dialogs/ThreeDReconstructionDialog.h
  dialogs/SparseCloudPostProcessDialog.h
  dialogs/WorkflowReportDialog.h
  dialogs/CameraConvertDialog.h
  dialogs/SurveyControlDialog.h
  dialogs/ObservationNetworkDialog.h
  dialogs/InitCameraPoseDialog.h
  dialogs/TriangulationDialog.h
  dialogs/DepthMapEstimateDialog.h
  dialogs/DepthFusionDialog.h
  dialogs/DenseCloudRefineDialog.h
  dialogs/MeshReconstructionDialog.h
  dialogs/TextureMappingDialog.h
  dialogs/ModelExportDialog.h
  dialogs/DenseMatchDialog.h
)

set(GUI_PROJECT_SOURCES
  project/archive/PlascanArchive.cpp
  project/data/ProjectData.cpp
  project/data/ProjectFilesManager.cpp
  project/io/ProjectIO.cpp
  project/services/BundleAdjustService.cpp
  project/services/ProjectCameraImportService.cpp
  project/services/ProjectResourceCleanupService.cpp
  project/support/ProjectSupportUtils.cpp
  project/support/ProjectBundleAdjustExecution.cpp
  project/support/ProjectBundleAdjustWorkflow.cpp
  project/support/ProjectCameraInitialization.cpp
  project/support/ProjectDashboardSummary.cpp
  project/support/ProjectDenseWorkflowConfig.cpp
  project/support/ProjectMetadataOperations.cpp
  project/support/ProjectReferenceDatasets.cpp
  project/support/ProjectReferenceTerrainBa.cpp
  project/support/ProjectResultRecords.cpp
  project/support/ProjectSfmWorkflow.cpp
  project/support/ProjectSparseWorkflow.cpp
  project/support/ProjectSurveyControl.cpp
  project/support/ProjectWorkflowUtils.cpp
  project/support/ProjectWorkflowReports.cpp
  project/manager/ProjectManager.cpp
  project/manager/ProjectDenseReconstructionManager.cpp
  project/manager/ProjectModelManager.cpp
  project/manager/ProjectReconstructionManager.cpp
  project/manager/ProjectTaskDispatcher.cpp
  project/manager/ProjectUiCommands.cpp
  project/manager/ProjectSparseReconstructionManager.cpp
  project/manager/ProjectTerrainProductsManager.cpp
  project/manager/ProjectCameraSetupManager.cpp
)

set(GUI_TASK_SOURCES
  tasks/FeatureExtractionRunner.cpp
  ../core/pipeline/FeatureMatchRunner.cpp
  ../core/pipeline/SFMService.cpp
)

set(GUI_DIALOG_SOURCES
  dialogs/MatchViewerDialog.cpp
  dialogs/MatchPairSelectorDialog.cpp
  dialogs/BundleAdjustDialog.cpp
  dialogs/CameraModel3DDialog.cpp
  dialogs/StereoProcessingDialog.cpp
  dialogs/OverlapAnalysisDialog.cpp
  dialogs/CreateDemDialog.cpp
  dialogs/MapProjectDialog.cpp
  dialogs/FeatureExtractionDialog.cpp
  dialogs/FeaturePairPlanner.cpp
  dialogs/VocabularyOverlapDialog.cpp
  dialogs/VocabularyOverlapDialog.ui
  dialogs/FeaturePointVisualizationDialog.cpp
  dialogs/FeatureMatchingDialog.cpp
  dialogs/ForwardIntersectionCheckDialog.cpp
  dialogs/ForwardIntersectionResultsDialog.cpp
  dialogs/DenseCloudDialog.cpp
  dialogs/ThreeDReconstructionDialog.cpp
  dialogs/ThreeDReconstructionDialog.ui
  dialogs/SparseCloudPostProcessDialog.cpp
  dialogs/MVSProgressDialog.cpp
  dialogs/WorkflowReportDialog.cpp
  dialogs/CameraConvertDialog.cpp
  dialogs/SurveyControlDialog.cpp
  dialogs/ObservationNetworkDialog.cpp
  dialogs/InitCameraPoseDialog.cpp
  dialogs/TriangulationDialog.cpp
  dialogs/DepthMapEstimateDialog.cpp
  dialogs/DepthFusionDialog.cpp
  dialogs/DenseCloudRefineDialog.cpp
  dialogs/MeshReconstructionDialog.cpp
  dialogs/TextureMappingDialog.cpp
  dialogs/ModelExportDialog.cpp
  dialogs/DenseMatchDialog.cpp
  dialogs/DenseMatchDialogUi.cpp
)
