# GUI 源文件清单

include(${CMAKE_CURRENT_LIST_DIR}/GuiDialogSources.cmake)

set(GUI_SOURCES
  main.cpp
  config/AppConfigManager.cpp
  config/ImageViewRotationSettings.cpp
  config/settings/WindowStateManager.cpp
  config/settings/RecentProjectsManager.cpp
  config/settings/DialogSettingStore.cpp
  main_window/MainWindow.cpp
  main_window/MainWindowLayout.cpp
  main_window/MainWindowMenuBindings.cpp
  main_window/MainWindowProjectBindings.cpp
  main_window/MainWindowProjectLifecycle.cpp
  main_window/MainWindowTaskStatus.cpp
  main_window/MainWindowUiState.cpp
  main_window/MainWindow.ui
  main_window/ModelDropSupport.cpp
  main_window/MenuWorkflowController.cpp
  main_window/ProjectUiHydrator.cpp
  main_window/ProjectTaskStatusController.cpp
  main_window/ProjectLifecyclePresenter.cpp
  main_window/FeatureVisualizationController.cpp
  main_window/ReconstructionWorkflowController.cpp
  main_window/TiePointWorkflowController.cpp
  main_window/WorkspacePanelController.cpp
  menu/ToolbarButton.cpp
  menu/MainMenu.cpp
  platform/ProjectFileIntegration.cpp
  platform/TaskbarProgressController.cpp
  runtime/PythonRuntimeManager.cpp
  runtime/GeospatialRuntimePaths.cpp
  runtime/BrowserDebugBridge.cpp
  runtime/TaskRuntimeService.cpp
  project/services/MetashapeCameraReferenceImporter.cpp
  reference/CameraReferenceController.cpp
  reference/CameraReferenceCsvExporter.cpp
  reference/CameraReferenceProjectIdentity.cpp
  reference/CameraReferenceTreeModel.cpp
  reference/MetashapeCameraReferenceSetBuilder.cpp
  reference/ProjectCameraReferenceRepository.cpp
  markers/ProjectMarkerRepository.cpp
  markers/MarkerUndoCommand.cpp
  markers/MarkerOverlayItems.cpp
  markers/MarkerWorkspaceController.cpp
  markers/MarkerWorkspaceDetection.cpp
  markers/MarkerWorkspaceView.cpp
  markers/MarkerProjectionPanel.cpp
  markers/MarkerReferencePanel.cpp
   markers/MarkerFocusMeasurementDialog.cpp
  markers/MarkerTaskRunner.cpp
  markers/MarkerDetectionJobBuilder.cpp
  markers/DetectMarkersDialog.cpp
  markers/MarkerDetectionReviewDialog.cpp
  markers/PrintMarkersDialog.cpp
  panels/LogPanel.cpp
  panels/LogEntryModel.cpp
  views/DepthOverlayData.cpp
  widgets/DepthOverlayController.cpp
  views/LayerFeatureLoader.cpp
  views/FeatureResidualLoader.cpp
  views/LayerImageLoader.cpp
  views/LayerOverlayItems.cpp
  views/LayerRenderer.cpp
  views/CameraSceneViewMath.cpp
  views/CameraSceneImageCache.cpp
  views/CameraSceneRhiResources.h
  views/SceneGeometryPreparation.cpp
  views/PointCloudEditPreparation.cpp
  views/PointCloudSnapshotIO.cpp
  views/CameraSceneWidget.cpp
  views/CameraSceneWidgetLegends.cpp
  views/CameraSceneWidgetOverlay.cpp
  views/ObjPointPreviewPreparation.cpp
  views/ObjRenderPreparation.cpp
  views/ObjStreamingLoader.cpp
  views/ObjStreamingLoaderAssembly.cpp
  views/TiePointVisualization.cpp
  widgets/CanvasWidget.cpp
  widgets/MaskEditor.cpp
  widgets/MaskEditor.h
  widgets/DataTreeWidget.cpp
  widgets/DataTreeContextMenu.cpp
  widgets/DataTreeModel.cpp
  widgets/DataTreePopulation.cpp
  widgets/DataTreeResourceAlignment.cpp
  widgets/DataTreeResourceMetadata.cpp
  widgets/DataTreeWidget.ui
  widgets/WorkspaceSectionIcons.cpp
  widgets/PhotoStripWidget.cpp
  widgets/ProjectDashboardWidget.cpp
  widgets/WorkPanelWidget.cpp
  widgets/ReferencePanelWidget.cpp
  widgets/ReferenceMarkerModels.cpp
  widgets/SelectionPropertiesWidget.cpp
  widgets/ImageViewWidget.cpp
  widgets/ImageViewWidget.ui
  widgets/MatchPointBatchItem.cpp
  widgets/MatchSpatialIndex.cpp
  widgets/MatchGpuRenderer.cpp
  widgets/MatchLineOverlay.cpp
  widgets/TaskStatusWidget.cpp
  widgets/DualImageViewer.cpp
  widgets/DualImageViewer.ui
  widgets/HenuBrandWidget.cpp
  widgets/ObservationNetworkView.cpp
  widgets/WorkspaceCenterWidget.cpp
  widgets/WorkspaceCenterWidget.ui
)

set(GUI_PROJECT_SOURCES
  config/settings/FileDialogStateManager.cpp
  project/services/BundleAdjustService.cpp
  project/services/ProjectCameraImportService.cpp
  project/services/ProjectSessionFacade.cpp
  project/services/ProjectTiePointResultService.cpp
  project/support/ProjectBundleAdjustExecution.cpp
  project/support/ProjectBundleAdjustWorkflow.cpp
  project/support/ProjectCameraInitialization.cpp
  project/support/ProjectDashboardSummary.cpp
  project/support/ProjectDepthBatchLineage.cpp
  project/support/ProjectModelResultPolicy.cpp
  project/support/ProjectModelTaskLifecycle.cpp
  project/support/ProjectRunArtifactValidator.cpp
  project/support/ProjectModelWorkflowPolicy.cpp
  project/support/ProjectMetadataOperations.cpp
  project/support/ProjectOpenGuard.cpp
  project/support/ProjectReferenceTerrainBa.cpp
  project/support/ProjectResultRecords.cpp
  project/support/ProjectSfmWorkflow.cpp
  project/support/ProjectSparseWorkflow.cpp
  project/support/ProjectSurveyControl.cpp
  project/support/ProjectWorkflowReports.cpp
  project/manager/ProjectManager.cpp
  project/manager/ProjectLifecycleController.cpp
  project/manager/ProjectMaskInferenceAdapter.cpp
  project/manager/ProjectMaskWorkflowController.cpp
  project/manager/ProjectPointCloudWorkflowController.cpp
  project/manager/ProjectModelManager.cpp
  project/manager/ProjectUiCommands.cpp
  project/manager/ProjectSparseReconstructionManager.cpp
  project/manager/ProjectTerrainProductsManager.cpp
  project/manager/ProjectTerrainRpcProducts.cpp
  project/manager/ProjectCameraSetupManager.cpp
)
