find_package(GTest REQUIRED)
include(GoogleTest)

add_executable(test_common_project_io test_project_io.cpp)
target_link_libraries(test_common_project_io PRIVATE
  plascan_common_project
  GTest::gtest_main
)
gtest_discover_tests(test_common_project_io DISCOVERY_MODE PRE_TEST)

add_executable(test_common_project_metadata test_project_metadata.cpp)
target_link_libraries(test_common_project_metadata PRIVATE
  plascan_common_project
  GTest::gtest_main
)
gtest_discover_tests(test_common_project_metadata DISCOVERY_MODE PRE_TEST)

add_executable(test_project_asset_importer test_project_asset_importer.cpp)
target_link_libraries(test_project_asset_importer PRIVATE
  plascan_common_project
  GTest::gtest_main
)
gtest_discover_tests(test_project_asset_importer DISCOVERY_MODE PRE_TEST)

add_executable(test_common_project_camera_io test_project_camera_io.cpp)
target_link_libraries(test_common_project_camera_io PRIVATE
  plascan_common_project
  camera
  GTest::gtest_main
)
gtest_discover_tests(test_common_project_camera_io DISCOVERY_MODE PRE_TEST)

add_executable(test_common_project_match_catalog test_project_match_catalog.cpp)
target_link_libraries(test_common_project_match_catalog PRIVATE
  plascan_common_project
  GTest::gtest_main
)
gtest_discover_tests(test_common_project_match_catalog DISCOVERY_MODE PRE_TEST)

add_executable(test_common_asp_match_point_reader test_asp_match_point_reader.cpp)
target_link_libraries(test_common_asp_match_point_reader PRIVATE
  plascan_common_project
  GTest::gtest_main
)
gtest_discover_tests(test_common_asp_match_point_reader DISCOVERY_MODE PRE_TEST)

add_executable(test_portable_project_format test_portable_project_format.cpp)
target_link_libraries(test_portable_project_format PRIVATE
  plascan_common_project
  GTest::gtest_main
)
gtest_discover_tests(test_portable_project_format DISCOVERY_MODE PRE_TEST)

add_executable(test_project_package_layout test_project_package_layout.cpp)
target_link_libraries(test_project_package_layout PRIVATE
  plascan_common_project
  GTest::gtest_main
)
gtest_discover_tests(test_project_package_layout DISCOVERY_MODE PRE_TEST)

add_executable(test_project_chunk_index test_project_chunk_index.cpp)
target_link_libraries(test_project_chunk_index PRIVATE
  plascan_common_project
  GTest::gtest_main
)
gtest_discover_tests(test_project_chunk_index DISCOVERY_MODE PRE_TEST)

add_executable(test_project_session test_project_session.cpp)
target_link_libraries(test_project_session PRIVATE
  plascan_common_project
  GTest::gtest_main
)
gtest_discover_tests(test_project_session DISCOVERY_MODE PRE_TEST)
